queries:

  - name: july-4th
    date-ranges:
      - 7/2-7/4

  - name: rmnp
    active: true
    date-ranges:
      - 7/25-7/27
    locations:
      - name: rocky mountain national park
        campgrounds:
          - name: glacier basin
          - name: moraine park

  - name: summer
    active: false
    date-ranges:
      - 04/28-04/29

locations:

  - name: yosemite
    campgrounds:
      - name: upper pines
        id: 232447
      - name: north pines
        id: 232449
        active: true
      - name: lower pines
        id: 232450
        active: true
      - name: hogdon meadows
        id: 232451
        active: false
      - name: crane flat
        id: 232452
        active: true
      - name: dry gulch
        id: 233842
        active: true
      - name: tuolumne meadows
        id: 232448
        active: true
      - name: camp4
        id: 10004152
        active: true
      - name: wawona
        id: 232446
        active: false
      - name: bridalveil
        id: 232453
        active: true

  - name: rocky mountain national park
    active: true
    campgrounds:
      - name: glacier basin
        id: 232462
      - name: moraine park
        id: 232463
      - name: timber creek
        id: 260552

  - name: sierra national forest
    active: true
    campgrounds:
      - name: dinkey creek
        id: 232136
      - name: catavee
        id: 232811
      - name: deer creek
        id: 232813
      - name: dorabelle
        id: 232821
      - name: fish creek
        id: 232820
      - name: kinnikinnick
        id: 232814
      - name: lupine
        id: 232802
      - name: soquel
        id: 232881
      - name: spring cove
        id: 232801
      - name: upper billy creek
        id: 232810
      - name: wishon bass lake
        id: 232911

  - name: zion
    active: true
    campgrounds:
      - name: south
        id: 272266
      - name: watchman
        id: 232445

  - name: bryce
    active: true
    campgrounds:
      - name: north
        id: 234058
      - name: sunset
        id: 234079

  - name: los padres
    active: true
    campgrounds:
      - name: kirk creek
        id: 233116
      - name: plaskett creek
        id: 231959

  - name: golden gate
    active: true
    campgrounds:
      - name: bicentennial
        id: 272229

  - name: stanislaus
    active: true
    campgrounds:
      - name: pinecrest
        id: 232254
      - name: sheep pass
        id: 232470
      - name: indian cove
        id: 232472

  - name: joshua tree
    active: true
    campgrounds:
      - name: jumbo rocks
        id: 272300

  - name: sequoia
    active: true
    campgrounds:
      - name: potwisha
        id: 249979
      - name: lodgepole
        id: 232461
      - name: buckeye flat
        id: 249982
      - name: sunset
        id: 234752
      - name: dorst
        id: 232460
      - name: sentinel
        id: 253917
      - name: crystal springs
        id: 251008

  - name: lassen
    active: true
    campgrounds:
      - name: manzanita lake
        id: 234039
      - name: summit lake south
        id: 234040
      - name: summit lake north
        id: 234041
      - name: butte
        id: 234156

  - name: pinnacles
    active: true
    campgrounds:
      - name: pinnacles
        id: 234015
